services:
  app:
    build: .
    container_name: locadora-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/plocadora
      SPRING_DATASOURCE_USERNAME: plocadora_user
      SPRING_DATASOURCE_PASSWORD: plocadora_pass
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION: "true"

      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 10
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 5
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 600000
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 1800000
    networks:
      - plocadora-network

  postgres:
    image: postgres:15-alpine
    container_name: plocadora-postgres
    environment:
      POSTGRES_DB: plocadora
      POSTGRES_USER: plocadora_user
      POSTGRES_PASSWORD: plocadora_pass
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - plocadora-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U plocadora_user -d plocadora"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  plocadora-network:
    driver: bridge
